apiVersion: apps/v1
kind: Deployment
metadata:
   name: deploy-appserver
spec:
  replicas: 2
  selector: 
    matchLables:
    deploy: app
  template:
    metadata:
     name: pod-app-d
     labels:
      deploy: app
    spec:
      containers:
        - image: pramdaspally/ursi:1.0
          name: appserver
          ports:  
           - containerPort: 8080 